[project]
name = "MicroGradEngine.py"
version = "0.1.0"
description = "Minimal scalar-valued AutoGrad engine in python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphviz>=0.21",
    "ipykernel>=6.29.5",
    "requests>=2.32.4",
]
